<a href="https://colab.research.google.com/github/Theanh130124/DeepLearning/blob/system_movies/Recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
movies = pd.read_csv('/dataset_movie.csv')





In [ ]:
movies.head(10) #Lay 10 hang DL dau

id                        title                     genre  \
0     278     The Shawshank Redemption               Drama,Crime   
1   19404  Dilwale Dulhania Le Jayenge      Comedy,Drama,Romance   
2     238                The Godfather               Drama,Crime   
3     424             Schindler's List         Drama,History,War   
4     240       The Godfather: Part II               Drama,Crime   
5  667257            Impossible Things              Family,Drama   
6     129                Spirited Away  Animation,Family,Fantasy   
7  730154               Your Eyes Tell             Romance,Drama   
8  372754     Dou kyu sei – Classmates         Romance,Animation   
9  372058                   Your Name.   Romance,Animation,Drama   

  original_language                                           overview  \
0                en  Framed in the 1940s for the double murder of h...   
1                hi  Raj is a rich, carefree, happy-go-lucky second...   
2                en  Spanning the years 1945 to 1955, a chronicle o...   
3                en  The true story of how businessman Oskar Schind...   
4                en  In the continuing saga of the Corleone crime f...   
5                es  Matilde is a woman who, after the death of her...   
6                ja  A young girl, Chihiro, becomes trapped in a st...   
7                ja  A tragic accident lead to Kaori's blindness, b...   
8                ja  Rihito Sajo, an honor student with a perfect s...   
9                ja  High schoolers Mitsuha and Taki are complete s...   

   popularity release_date  vote_average  vote_count  
0      94.075   1994-09-23           8.7       21862  
1      25.408   1995-10-19           8.7        3731  
2      90.585   1972-03-14           8.7       16280  
3      44.761   1993-12-15           8.6       12959  
4      57.749   1974-12-20           8.6        9811  
5      14.358   2021-06-17           8.6         255  
6      92.056   2001-07-20           8.5       13093  
7      51.345   2020-10-23           8.5         339  
8      14.285   2016-02-20           8.5         239  
9     158.270   2016-08-26           8.5        8895

In [ ]:
movies.describe() #Thong ke DL


id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [ ]:
movies.info() #Thong tin DL

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 10000 non-null  int64  
 1   title              10000 non-null  object 
 2   genre              9997 non-null   object 
 3   original_language  10000 non-null  object 
 4   overview           9987 non-null   object 
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object 
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64  
dtypes: float64(2), int64(2), object(5)
memory usage: 703.3+ KB


In [ ]:
movies.isnull().sum() #Tong so DL null

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [ ]:
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
# id,title,genre,overview  -> day la cac cot quan trong , cac cot con lai loai bo
movies = movies[['id','title','genre','overview']]
movies

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                 genre  \
0                                          Drama,Crime   
1                                 Comedy,Drama,Romance   
2                                          Drama,Crime   
3                                    Drama,History,War   
4                                          Drama,Crime   
...                                                ...   
9995                          Action,Adventure,Fantasy   
9996  Action,TV Movie,Science Fiction,Comedy,Adventure   
9997                        Action,Science Fiction,War   
9998                    Adventure,Fantasy,Action,Drama   
9999                             Thriller,Action,Crime   

                                               overview  
0     Framed in the 1940s for the double murder of h...  
1     Raj is a rich, carefree, happy-go-lucky second...  
2     Spanning the years 1945 to 1955, a chronicle o...  
3     The true story of how businessman Oskar Schind...  
4     In the continuing saga of the Corleone crime f...  
...                                                 ...  
9995  The story follows the adventures of Aang, a yo...  
9996  The sharks take bite out of the East Coast whe...  
9997  During World War II, a brave, patriotic Americ...  
9998  A man named Farmer sets out to rescue his kidn...  
9999  Seeking justice for his partner’s murder by an...  

[10000 rows x 4 columns]

Feature Section Part

In [ ]:
movies['tags']=movies['overview']+movies['genre'] #nhom chung thanh tag
movies

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                 genre  \
0                                          Drama,Crime   
1                                 Comedy,Drama,Romance   
2                                          Drama,Crime   
3                                    Drama,History,War   
4                                          Drama,Crime   
...                                                ...   
9995                          Action,Adventure,Fantasy   
9996  Action,TV Movie,Science Fiction,Comedy,Adventure   
9997                        Action,Science Fiction,War   
9998                    Adventure,Fantasy,Action,Drama   
9999                             Thriller,Action,Crime   

                                               overview  \
0     Framed in the 1940s for the double murder of h...   
1     Raj is a rich, carefree, happy-go-lucky second...   
2     Spanning the years 1945 to 1955, a chronicle o...   
3     The true story of how businessman Oskar Schind...   
4     In the continuing saga of the Corleone crime f...   
...                                                 ...   
9995  The story follows the adventures of Aang, a yo...   
9996  The sharks take bite out of the East Coast whe...   
9997  During World War II, a brave, patriotic Americ...   
9998  A man named Farmer sets out to rescue his kidn...   
9999  Seeking justice for his partner’s murder by an...   

                                                   tags  
0     Framed in the 1940s for the double murder of h...  
1     Raj is a rich, carefree, happy-go-lucky second...  
2     Spanning the years 1945 to 1955, a chronicle o...  
3     The true story of how businessman Oskar Schind...  
4     In the continuing saga of the Corleone crime f...  
...                                                 ...  
9995  The story follows the adventures of Aang, a yo...  
9996  The sharks take bite out of the East Coast whe...  
9997  During World War II, a brave, patriotic Americ...  
9998  A man named Farmer sets out to rescue his kidn...  
9999  Seeking justice for his partner’s murder by an...  

[10000 rows x 5 columns]

In [ ]:
new_data = movies.drop(columns=['overview','genre']) #Giu id va title de truyen qua API de lay ra ds phim (vd tra ve ten phim )
new_data

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                   tags  
0     Framed in the 1940s for the double murder of h...  
1     Raj is a rich, carefree, happy-go-lucky second...  
2     Spanning the years 1945 to 1955, a chronicle o...  
3     The true story of how businessman Oskar Schind...  
4     In the continuing saga of the Corleone crime f...  
...                                                 ...  
9995  The story follows the adventures of Aang, a yo...  
9996  The sharks take bite out of the East Coast whe...  
9997  During World War II, a brave, patriotic Americ...  
9998  A man named Farmer sets out to rescue his kidn...  
9999  Seeking justice for his partner’s murder by an...  

[10000 rows x 3 columns]

In [ ]:
#NLP
# 1.Bag of word
# 2.TFIDE
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000,stop_words='english') #Chuyen doi vanban thanh vector cho may hieu  # loại bỏ 'this', 'is', 'in', 'and' do english
vector = cv.fit_transform(new_data['tags'].values.astype('U')).toarray() # values.astype('U'): ép kiểu dữ liệu về unicode string (bắt buộc nếu có NaN hoặc dữ liệu không chuẩn).

#fit_transform(): học các từ xuất hiện trong cột tags, rồi chuyển thành vector.


print(cv.get_feature_names_out()) #IN ra bag of word no lay duoc
print(vector)   #in ra mang vector

['000' '007' '10' ... 'zone' 'zones' 'zoo']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
vector.shape


(10000, 10000)

#Cosine similarity (độ tương đồng cosin) là một phép đo được sử dụng để tính mức
# độ tương đồng giữa hai vector trong không gian vector bằng cách đo cosin của góc giữa chúng


#🔍 Ví dụ đơn giản:
Giả sử hai vector:

A = [1, 2, 3]

B = [4, 5, 6]

Áp dụng công thức:

Dot product:
𝐴
⋅
𝐵
=
1
∗
4
+
2
∗
5
+
3
∗
6
=
32
A⋅B=1∗4+2∗5+3∗6=32

Norm A:
∥
𝐴
∥
=
1
2
+
2
2
+
3
2
=
14
∥A∥=
1
2
 +2
2
 +3
2

​
 =
14
​


Norm B:
∥
𝐵
∥
=
4
2
+
5
2
+
6
2
=
77
∥B∥=
4
2
 +5
2
 +6
2

​
 =
77
​


Cosine similarity
=
32
14
×
77
≈
0.9746
Cosine similarity=
14
​
 ×
77
​

32
​
 ≈0.9746
📘 Đặc điểm:
Giá trị nằm trong khoảng từ -1 đến 1:

Gần 1: rất tương đồng

Gần 0: không tương đồng

Gần -1: hoàn toàn trái ngược (hiếm gặp trong xử lý văn bản)

In [ ]:
#No so sanh theo the loai trong tag(vd phim theo Actions(hanh dong)) -> KC 2 vecto cang gan cang giong nhau

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector) #Tinh do tuong dong cosin
similarity


array([[1.        , 0.05634362, 0.13041013, ..., 0.07559289, 0.11065667,
        0.06900656],
       [0.05634362, 1.        , 0.07715167, ..., 0.        , 0.03636965,
        0.        ],
       [0.13041013, 0.07715167, 1.        , ..., 0.02300219, 0.0673435 ,
        0.09449112],
       ...,
       [0.07559289, 0.        , 0.02300219, ..., 1.        , 0.03253   ,
        0.03042903],
       [0.11065667, 0.03636965, 0.0673435 , ..., 0.03253   , 1.        ,
        0.04454354],
       [0.06900656, 0.        , 0.09449112, ..., 0.03042903, 0.04454354,
        1.        ]])

In [ ]:
# #Code nay test dung chay lai

# #Lay chi muc theo title
# new_data[new_data['title'] =="The Godfather"].index[0]
# # new_data[new_data['title'] =="The Godfather"].index[0] #lay id

np.int64(2)

 #Lấy danh sách tất cả phim và sắp xếp chúng theo độ tương đồng với phim thứ 2 (index = 2) trong ma trận similarity.

#Dòng này giúp chọn ra những phim nào giống với phim có index = 2 nhất (ở đây bạn nên thay bằng index của "The Godfather" để đúng mục tiêu).

In [ ]:
#Code nay test dung chay lai

distance = sorted(list(enumerate(similarity[2])),reverse=True , key=lambda vector:vector[1]) #keys=lambda vector:vector[1] do similarities = [(0, 0.9), (1, 0.3), (2, 0.8)] la index , score
#lay vector[1] chinh la lay score de so sanh ,,
#tao ranh enumerate(similarity[2] tuple(index,score)

#Truy cap 5 phim gan nhat (giong nhat)
for i in distance[1:6]: # bỏ i=0 vì đó chính là phim đang chọ
    print(new_data.iloc[i[0]].title) #Lay hang thu 0 cua cot title  vd : df.iloc[2]['year']   # Lấy năm của dòng thứ 3: 2010



The Godfather
The Godfather: Part II
Blood Ties
Joker
Bomb City


In [ ]:
#Fuction recommender
def recommand(movies):
  index = new_data[new_data['title'] == movies].index[0]
  distance = sorted(list(enumerate(similarity[index])),reverse=True , key=lambda vector:vector[1]) #similarity index
  for i in distance[1:6]:
    print(new_data.iloc[i[0]].title)

In [ ]:
recommand("Iron Man")

The Godfather
The Godfather: Part II
Blood Ties
Joker
Bomb City


Chế độ	Ý nghĩa
'r'	Đọc file văn bản
'w'	Ghi file văn bản (xóa nội dung cũ nếu có)
'a'	Ghi nối thêm vào cuối file
'rb'	Đọc file nhị phân (read binary)
'wb'	Ghi file nhị phân (write binary)



thì file movies_list.pkl sẽ được lưu tại thư mục hiện tại (working directory) — tức là nơi mà bạn đang chạy file .py hoặc notebook.

In [77]:
import pickle
pickle.dump(new_data,open('movies_list.pkl','wb'))  #Luu file data (da tien xu ly dl) -> Luu vao noo
pickle.dump(similarity,open('similarity.pkl','wb')) #Luu file do tuong dong
pickle.load(open('movies_list.pkl','rb')) #Doc file

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                   tags  
0     Framed in the 1940s for the double murder of h...  
1     Raj is a rich, carefree, happy-go-lucky second...  
2     Spanning the years 1945 to 1955, a chronicle o...  
3     The true story of how businessman Oskar Schind...  
4     In the continuing saga of the Corleone crime f...  
...                                                 ...  
9995  The story follows the adventures of Aang, a yo...  
9996  The sharks take bite out of the East Coast whe...  
9997  During World War II, a brave, patriotic Americ...  
9998  A man named Farmer sets out to rescue his kidn...  
9999  Seeking justice for his partner’s murder by an...  

[10000 rows x 3 columns]